### ISSUE TITLE
Web server crash + Blank web page graph

### ISSUE THREAD

**Issue by scilib** [rydercalmdown/pi_air_quality_monitor#18]
The web server crash appears to be caused by a hard-coded URL (a hard-coded IP address).
I've submitted a pull request to fix this.

Pull request [https://github.com/rydercalmdown/pi_air_quality_monitor/pull/17](https://github.com/rydercalmdown/pi_air_quality_monitor/pull/17)

Once I made this change, my web server worked fine, e.g. on localhost
<pre>http://127.0.0.1:8000/</pre>

This should address the problem reported in Issue #1 .

Thanks to Issue #3 for this fix.

However be aware the web page does not auto-refresh.  Even if everything is working properly, it will appear blank until you manually refresh it.  If you manually refresh after a minute or so you should see data for PM2.5 and PM10 plotted on the chart, with new data added whenever you do a new manual refresh.

Manual refresh should address the problem reported in Issue #8 .

**Comment by mindfury** [comment]
You beat me to this... I noticed the same thing and changed the JavaScript trying to pull from some 10. address.  Great find!
